### PR TITLE
test

### PR DESCRIPTION
**Pull request by Denisovitch**

### CODE REVIEW

**Review by NatNaz — COMMENTED** [review]
where there are red minuses in the end of the code, mustn't be there a new clear line?

**Review by NatNaz — COMMENTED** [review]
where there are red minuses in the end of the code, mustn't be there a new clear line?

**Review by NatNaz — COMMENTED** [review]
task5/5_2.js 
image
i would rename the variable without includind 'string' or adding smth like arr, for example stringToArr...

**Comment by Denisovitch** [comment]
> where there are red minuses in the end of the code, mustn't be there a new clear line?

what do you mean?

**Comment by Denisovitch** [comment]
> task5/5_2.js  i would rename the variable without includind 'string' or adding smth like arr, for example stringToArr...
ok. thk. i made it. i changed name of the variable

**Review by NatNaz — COMMENTED** [review]
task5/5_7.js
method .indexOf would be shorter

**Review by NatNaz — COMMENTED** [review]
task5/5_9.js

1. variable endOfNumberAge doesn't appear in the code, maybe it was considered to apper at str18?

**Comment by NatNaz** [comment]
> > where there are red minuses in the end of the code, mustn't be there a new clear line?
> 
> what do you mean?
image

**Comment by Denisovitch** [comment]
> 1. variable endOfNumberAge doesn't appear in the code, maybe it was considered to apper at str18?

you can use a variable for a loop, you can use a number.

**Comment by Denisovitch** [comment]
> > > where there are red minuses in the end of the code, mustn't be there a new clear line?
> > 
> > 
> > what do you mean?
> > image

**Comment by Denisovitch** [comment]
> .indexOf

is it shorter or more correct?)))

is it shorter or more correct? as a rule, it should be faster...
from stackoverflow ---Head-on search
Let's just try to go through the elements of the array until we meet what we need. As always, the simplest solution is on average the fastest....

**Pull request merged**
